system:
  n: 4
  f: 1

replicas:
  server1:
    senderId: 0
    host: 127.0.0.1
    ports:
      consensus: 10001
      client: 11001
  server2:
    senderId: 1
    host: 127.0.0.1
    ports:
      consensus: 10002
      client: 11002
  server3:
    senderId: 2
    host: 127.0.0.1
    ports:
      consensus: 10003
      client: 11003
  server4:
    senderId: 3
    host: 127.0.0.1
    ports:
      consensus: 10004
      client: 11004

clients:
  client:
    senderId: 100
    host: 127.0.0.1
    requestTimeoutMs: 0
    knownReplicas:
      - server1
      - server2
      - server3
      - server4
  client2:
    senderId: 101
    host: 127.0.0.1
    requestTimeoutMs: 0
    knownReplicas:
      - server1
      - server2
      - server3
      - server4
  client3:
    senderId: 102
    host: 127.0.0.1
    requestTimeoutMs: 0
    knownReplicas:
      - server1
      - server2
      - server3
      - server4

timeouts:
  viewChangeMs: 1000
  clientCommandWaitMs: 800
  thresholdRoundMs: 800
  fetchNodeMs: 300

keys:
  root: runtime/keys

storage:
  blocksRoot: runtime/storage
