package pt.ulisboa.depchain.integration.byzantine;

public enum ByzantineAttackMode {
  DROP_ALL_MESSAGES, INVALID_NEW_VIEW, SPOOFED_REPLICA_SENDER_ID, INVALID_PREPARE_VOTE, INVALID_PRE_COMMIT_VOTE, INVALID_COMMIT_VOTE, STALE_PREPARE_VOTE, STALE_PRE_COMMIT_VOTE, STALE_COMMIT_VOTE, INVALID_PREPARE_PROPOSAL_QC, INVALID_PRE_COMMIT_QC, INVALID_COMMIT_QC, INVALID_DECIDE_QC
}
